version: "3.9"

services:
  node:
    image: node:18.17.1-alpine
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./client
        target: /app
    tty: true
    working_dir: /app
