-- Create "password_reset_tokens" table
CREATE TABLE `password_reset_tokens` (`email` varchar(255) NOT NULL, `token` varchar(255) NOT NULL, `created_at` timestamp NULL, PRIMARY KEY (`email`)) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- Create "personal_access_tokens" table
CREATE TABLE `personal_access_tokens` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `tokenable_type` varchar(255) NOT NULL, `tokenable_id` bigint unsigned NOT NULL, `name` varchar(255) NOT NULL, `token` varchar(64) NOT NULL, `abilities` text NULL, `last_used_at` timestamp NULL, `expires_at` timestamp NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`), UNIQUE INDEX `personal_access_tokens_token_unique` (`token`), INDEX `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`, `tokenable_id`)) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- Create "users" table
CREATE TABLE `users` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `email` varchar(255) NOT NULL, `email_verified_at` timestamp NULL, `password` varchar(255) NOT NULL, `remember_token` varchar(100) NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`), UNIQUE INDEX `users_email_unique` (`email`)) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- Create "events" table
CREATE TABLE `events` (`id` int unsigned NOT NULL AUTO_INCREMENT, `title` varchar(255) NOT NULL, `body` varchar(2047) NOT NULL, `user_id` bigint unsigned NOT NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`), INDEX `user_id` (`user_id`), CONSTRAINT `events_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
-- Create "event_user" table
CREATE TABLE `event_user` (`event_id` int unsigned NOT NULL, `user_id` bigint unsigned NOT NULL, INDEX `event_id` (`event_id`), INDEX `user_id` (`user_id`), CONSTRAINT `event_user_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE CASCADE, CONSTRAINT `event_user_ibfk_2` FOREIGN KEY (`event_id`) REFERENCES `events` (`id`) ON UPDATE CASCADE ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
